sudo: false
language: d
d:
  - dmd
  - ldc
env:
  - VERSION=min
  - VERSION=max
script:
  - dub test :common --compiler=$DC
  - rdmd ./d-test-utils/test_with_package.d libdparse -- dub test --compiler=$DC
  - rdmd ./d-test-utils/test_with_package.d libdparse -- dub build --config=lib --compiler=$DC
  - rdmd ./d-test-utils/test_with_package.d libdparse -- dub build --config=exe --compiler=$DC
